### ISSUE TITLE
Docker file

### ISSUE THREAD

**Issue by SergeMv** [daijifeng001/MNC#10]
Would you consider creating a docker (or nvidia-docker) file so the compilation gets easier?

**Comment by Oh233** [comment]
Currently we don't have such plan.

**Comment by weitianhan** [comment]
@SergeMv  In fact I have created a docker file for this MNC project.

**Comment by SergeMv** [comment]
@weitianhan Where could it be found? I searched MNC for a dockerfile and have not found it.
