### ISSUE TITLE
Help? Training  my own dataset is done, test on images error : Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered *** Check failure stack trace: ***

### ISSUE THREAD

**Issue by brisker** [daijifeng001/MNC#23]
I1020 12:30:46.939435 28978 net.cpp:865] Ignoring source layer rpn_loss_bbox
I1020 12:30:46.939491 28978 net.cpp:865] Ignoring source layer rpn_loss_cls
I1020 12:30:46.939963 28978 net.cpp:865] Ignoring source layer seg_cls_score_ext_seg_cls_score_ext_0_split
I1020 12:30:46.939996 28978 net.cpp:865] Ignoring source layer seg_cls_score_seg_cls_score_0_split
F1020 12:30:47.198374 28978 syncedmem.hpp:18] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
*** Check failure stack trace: ***

**Comment by hgaiser** [comment]
For future reference, I'm assuming you ran out of memory. Are you running VGG16? I believe you require at least 6GB of memory to train VGG16.
