### ISSUE TITLE
How to make the initial weight vgg16.mask.caffemodel ?

### ISSUE THREAD

**Issue by songkyungmin** [daijifeng001/MNC#24]
I want to apply another dataset, but i don't know make  mask.caffemodel. 

Any advice?

**Comment by Oh233** [comment]
That model is the image-net pre-trained vgg model. I just copy weights of fc6 fc7 to fc6_mask, fc7_mask. You may just use it as a pre-trained model.

**Comment by songkyungmin** [comment]
Thanks! Have a nice day
