### ISSUE TITLE
SBD Link

### ISSUE THREAD

**Issue by bharath272** [daijifeng001/MNC#3]
Hi Jifeng,
Owing to my webpage moving out of Berkeley, the landing page for the SBD dataset is now at http://googledrive.com/host/0ByUkob0WA1-NQi1sNlg4WkJQbTg/codes/SBD/download.html
Could you update the link in the README (and wherever else it appears)?

**Comment by Oh233** [comment]
Thank you for your information. I already fixed it.

**Comment by isarker** [comment]
hi @Oh233 , can you give me little suggestion for how to label data for your MNC? in faster rcnn case it support .xml file. here you use .mat. so how can i label my own data to make boundaries and segmentation. thanks in advance.

**Comment by DrSleep** [comment]
Hi @bharath272, unfortunately, the link is broken. Could you please provide an alternative one?

**Comment by bharath272** [comment]
http://home.bharathh.info/pubs/codes/SBD/download.html

**Comment by DrSleep** [comment]
Thank you!
