### ISSUE TITLE
F0102 20:50:54.342540  4460 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by wolf943134497** [daijifeng001/MNC#32]
I0102 20:50:53.544600  4460 net.cpp:865] Ignoring source layer rpn_loss_bbox
I0102 20:50:53.544636  4460 net.cpp:865] Ignoring source layer rpn_loss_cls
I0102 20:50:53.544839  4460 net.cpp:865] Ignoring source layer seg_cls_score_ext_seg_cls_score_ext_0_split
I0102 20:50:53.544852  4460 net.cpp:865] Ignoring source layer seg_cls_score_seg_cls_score_0_split
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/2008_000533.jpg
F0102 20:50:54.342540  4460 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
已放弃 (核心已转储)
I use  GPU has  8G of RAM(GTX 1070) .not use cuDNN .because cuDNN v5 not support .
The problem is solved by using cuDNN v4.

**Comment by SmualWang** [comment]
I think it's not only cudnn v5 problem, py-faster-rcnn can solve the problem with cudnn v5  [https://github.com/rbgirshick/py-faster-rcnn/issues/237](url) but still got the error , I have solve the problem by modifying the mnc_config.py (in MNC/lib) to reduce the some number to reduce the cost of GPU memory
