### ISSUE TITLE
How to do training with MNC on another data set?

### ISSUE THREAD

**Issue by MinaRe** [daijifeng001/MNC#5]
Dear @daijifeng001  @Oh233 @liyi14 

Thanks a lot for sharing your great job.
Can you please explain how to do training on another data set, I want to know more detail about Annotation file format and Image set,etc.

Best regrads
mina

**Comment by daijifeng001** [comment]
Hi, you need to re-implement the data provider (imdb_from_XXX, roidb_from_XXX) for the new dataset.

**Comment by MinaRe** [comment]
Hi @daijifeng001 , Can you please tell me If I want to do the training on my dataset should I prepare it like this structure? and How can I prepare .mat files? 
VOCdevkit2007
|-- data
    |-- Annotations
         |-- *.txt (Annotation files)
    |-- JPEGImages
         |-- *.jpg (Image files)
    |-- ImageSets
         |-- Layout
              |-- test.txt ,train.txt, trainval.txt, val.txt
         |-- Main
              |-- XXX_test.txt ,XXX_train.txt, XXX_trainval.txt, XXX_val.txt 
         |-- Segmentation
              |-- test.txt ,train.txt, trainval.txt, val.txt
    |-- SegmentationClass
         |-- *.png (mask files)
    |-- SegmentationObject
         |-- *.png (mask files)


VOCdevkitSDS
|-- dataset
    |-- cls
         |-- *.mat (?)
    |-- img
         |-- *.jpg (Image files)
    |-- inst
         |-- *.mat (?)
    |-- train.txt,  val.txt

Thanks in advance.

**Comment by daijifeng001** [comment]
There are many details you need to pay attention too, although they are not hard or challenging. You may carefully review our code and do trial-and-error on your new dataset.

**Comment by MinaRe** [comment]
Dear @daijifeng001 
I have received this error on my data when it makes 'maskdb', 
Can you please kindly help me.
Thanks in Advance.

 File "/data/Workspace/MNC/tools/../lib/datasets/cell_cancer.py", line 98, in set_mask_handler
    method = eval('self.' + method + '_maskdb')
  File "<string>", line 1, in <module>
AttributeError: 'CellCancerDet' object has no attribute 'gt_maskdb'

**Comment by Oh233** [comment]
@MinaRe 
Did you implement your gt_maskdb function like https://github.com/daijifeng001/MNC/blob/master/lib/datasets/pascal_voc_seg.py#L52 ?

**Comment by MinaRe** [comment]
@Oh233 
I didn't reimplement, I am using same function.

**Comment by MinaRe** [comment]
@Oh233 
Thanks for answering my question,

Is this problem because of weight initialization or Should I change the MASK_SIZE??

F1012 19:09:14.293640 16881 sigmoid_cross_entropy_loss_layer.cpp:23] Check failed: bottom[0]->count() == bottom[1]->count() (4 vs. 441) SIGMOID_CROSS_ENTROPY_LOSS layer inputs must have the same count.
*** Check failure stack trace: ***
./experiments/scripts/mnc_5stage.sh: line 35: 16881 Aborted                 (core dumped) ./tools/train_net.py --gpu ${GPU_ID} --solver models/${NET}/mnc_5stage/solver.prototxt --imdb ${DATASET_TRAIN} --iters ${ITERS} --cfg experiments/cfgs/${NET}/mnc_5stage.yml ${EXTRA_ARGS}

**Comment by MinaRe** [comment]
Hey @Oh233 
Do you have any idea or solution for this error ?

I1013 16:20:50.908434  3511 solver.cpp:229] Iteration 0, loss = 6.69711
I1013 16:20:50.908483  3511 solver.cpp:245]     Train net output #0: accuracy_det = 0
I1013 16:20:50.908488  3511 solver.cpp:245]     Train net output #1: accuracy_det_ext = 0.333333
I1013 16:20:50.908495  3511 solver.cpp:245]     Train net output #2: accuracy_seg = 0
I1013 16:20:50.908500  3511 solver.cpp:245]     Train net output #3: accuracy_seg_ext = 0.666667
I1013 16:20:50.908510  3511 solver.cpp:245]     Train net output #4: bbox_loss = 0 (* 1 = 0 loss)
I1013 16:20:50.908520  3511 solver.cpp:245]     Train net output #5: bbox_loss_ext = 0.00583208 (* 1 = 0.00583208 loss)
I1013 16:20:50.908529  3511 solver.cpp:245]     Train net output #6: cls_loss = 0.854479 (* 1 = 0.854479 loss)
I1013 16:20:50.908536  3511 solver.cpp:245]     Train net output #7: cls_loss_ext = 0.924694 (* 1 = 0.924694 loss)
I1013 16:20:50.982221  3511 solver.cpp:245]     Train net output #8: loss_mask = 0 (* 2 = 0 loss)
I1013 16:20:50.982245  3511 solver.cpp:245]     Train net output #9: loss_mask_ext = 0.692961 (* 2 = 1.38592 loss)
I1013 16:20:50.982254  3511 solver.cpp:245]     Train net output #10: rpn_cls_loss = 0.877503 (* 1 = 0.877503 loss)
I1013 16:20:50.982261  3511 solver.cpp:245]     Train net output #11: rpn_loss_bbox = 0.635716 (* 1 = 0.635716 loss)
I1013 16:20:50.982270  3511 solver.cpp:245]     Train net output #12: seg_cls_loss = 1.0599 (* 1 = 1.0599 loss)
I1013 16:20:50.982278  3511 solver.cpp:245]     Train net output #13: seg_cls_loss_ext = 0.517544 (* 1 = 0.517544 loss)
I1013 16:20:50.982286  3511 sgd_solver.cpp:106] Iteration 0, lr = 0.001
**Unhandled signal in divisionErrorHandler()**
./experiments/scripts/mnc_5stage.sh: line 36:  3511 Aborted

**Comment by brisker** [comment]
@MinaRe 
Have you got it done?

**Comment by MinaRe** [comment]
@brisker 
Yes I did training and achieved very good result, thanks for sharing your great job,

**Comment by brisker** [comment]
@MinaRe 
What kind of cell image did you use as your training dataset? Microscopy? Or other types?

**Comment by MinaRe** [comment]
Yes, Microscopy images.

**Comment by brisker** [comment]
@MinaRe 
Histopathology H&E stained?

**Comment by MinaRe** [comment]
HE stain from charite hospital in berlin

**Comment by jeremy-rutman** [comment]
You mentioned that "you need to re-implement the data provider (imdb_from_XXX, roidb_from_XXX) for the new dataset."  
I don't see any function called imdb_from*  anywhere in the repo.  I think I need to re-implement MNC/pascal_voc_det.py and MNC/pascal/voc_seg.py to use my own data, is this correct?
Alternatively I could just replace the current data with other data in the exact same format, namely replace the file MNC/data/cache/voc_2012_train_gt_roidb.pkl with mine and likewise  voc_2012_train_gt_maskdb.pkl  .    The former contains entries like:
 ```
{'boxes': array([[265, 144, 290, 213]], dtype=uint16), 'gt_overlaps': <1x21 sparse matrix of type '<type 'numpy.float32'>'
	with 1 stored elements in Compressed Sparse Row format>, 'gt_classes': array([3], dtype=int32), 'flipped': False}
```
The boxes is clear enough but the 'gt_overlaps' is not so clear to me. There are 21 so it could be overlap between classes, on the other hand the mask_size  is also 21 so maybe its overlap of mask elements. I will try to get the sparse matrix data for more  clues. 
The gt_maskdb.pkl  contains entries like: 
```

{'mask_max': [26, 70], 'gt_masks': [array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       ..., 
       [False,  True,  True, ..., False, False, False],
       [False,  True,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)], 'flipped': False}

```
Which has a binary mask , it looks like, but also 'mask_max' which is mysterious. Any hints welcome, in the meantime I will continue digging.

**Comment by Oh233** [comment]
1. imdb from and roidb_from may be our jargon for the data provider's name. So yes, you need to implement MNC/pascal_voc_det.py

2. in gt_overlap, it is 'overlap between classes'.

3. For the mask_max, this is because, I want to pass the mask before re-size to 21x21 to top layers. At this stage, mask size will be num_mask x 1 x mask_height x mask_width.

But different masks have different h/w, so I generate a blob according to the max value (num_mask x 1 x max(mask_height) x max(mask_width)) over each mask and pad with 0.

**Comment by jeremy-rutman** [comment]
Ok thanks . We have written a  script to generate the roidb and maskdb .   We still have a question or two:
1. in roidb.pkl, there is the 'boxes' field, is it [x_left,y_top,w,h] or [x_center,y_center,w,h] or what??
2.  in roidb.pkl , there is the gt_overlaps field. We never saw an example without an overlap for every box, so it seems this isnt really overlap but rather something along the lines of 'which category appears in which bounding box'.   Anyway in our data we have only at most one instance of a given item in a given image. For example we have a dog, class 3 in the first bb and a dress, class 5 in the second bb.  For this case the desired matrix would be:
```
[0 0 0 1 0 0 ]
[0 0 0 0 0 1] 
```
and then we turn it to sparse using 

```
from scipy import sparse
sA = sparse.csr_matrix(A)
```
which comes out looking like 
(0,3) 1
(1,5) 1
when printed .  Is this correct ?

TIA Jeremy

**Comment by ogail** [comment]
@MinaRe could you share link/instructions on how did you create your own dataset of classes to voc mat format?
