### ISSUE TITLE
Training MNC on MS COCO dataset

### ISSUE THREAD

**Issue by brade31919** [daijifeng001/MNC#6]
Dear @daijifeng001 @Oh233 @liyi14 

Thanks a lot for sharing your marvelous project.  
I just started to learn deep learning several weeks ago.
I have some problem about training MNC on MS COCO dataset.

First, regarding preparing dataset, I found I should modify the code providing data (MNC_ROOT/lib/datasets/* ). Beside datasets, is there any code need to be re-implement?

Second, there are some functions to do evaluation in MNC_ROOT/lib/datasets/pascal_voc_seg.py. How can I do evaluation on MS COCO for instance-aware semantic segmentation? I can't find api to evaluate segmentation (only api for evaluating detection in COCO api @@).

Third, could you please provide your data provider of MS COCO? There are few examples about providing data for instance-aware semantic segmentation and it is quite hard for me to do this.

Sorry for asking so many questions. I am quite new to deep learning and caffe, so there are many details I don't know.

Best regards
沅

**Comment by daijifeng001** [comment]
Hi, we have not not implement a public python version of coco data provider. You can make use of the API provided by COCO. Then implementing the coco data provider is not that hard.

**Comment by brade31919** [comment]
Thanks a lot!!
I have one more little question.
I can find some examples of using coco api to do evaluation in faster rcnn case. However, in that case, it needs only detection evaluation part. In MNC case, I found there are some difference between pascal_voc_det and pascal_voc_seg about evaluation. In coco api, I can find the evaluation function correspond to which in pascal_voc_det, but I can't find the function correspond to evaluation about evaluating segmentation @@
Or...do I have wrong understanding on the coco api?
Thank you for answering so many question!!

**Comment by daijifeng001** [comment]
Hi, the API are shared for detection and instance segmentation.
