### ISSUE TITLE
Question: ResNet-101 and MS COCO

### ISSUE THREAD

**Issue by MrBlubb** [daijifeng001/MNC#7]
Hi daijifeng001,

thank you for sharing this wonderful library.

Do you intend to release the (pre-trained) network, which won the 1st place in the COCO segmentation track? (i.e. the MNC using ResNet-101, COCO trainval images, context modeling and multi-scale testing) 

Carrying out these steps looks quite time-consuming / complex. I can imagine, that the community would really benefit from publishing this pre-trained network.   

Best regards,
Sebastian

**Comment by daijifeng001** [comment]
Hi, thanks for your suggestion. But I cannot release such files for the time being. Because our internal code is based on a heavily modified version of caffe and matlab. I do not have sufficient time for releasing such code. Sorry for that.

**Comment by hgaiser** [comment]
Just out of curiosity, what kind of modifications are you referring to?
