### ISSUE TITLE
caffe-mnc folder is empty

### ISSUE THREAD

**Issue by sodaGH** [daijifeng001/MNC#71]
I have build my Caffe and pycaffe. When I build the caffe-mnc, this folder is empty. Should I copy the Makefile in `MNC-master/lib` ?
And I wonder whether I make the `$MNC_ROOT/lib` successfully. When I make the file, the record are as followed:
![11111](https://user-images.githubusercontent.com/18156614/30521908-36482726-9bfa-11e7-94c4-26b63407f7aa.png)

Could anyone tell me is the `make` process successful? Thanks a lot!

**Comment by mldm4** [comment]
Make sure to clone the MNC repository with` --recursive` flag like this:
`git clone --recursive https://github.com/daijifeng001/MNC.git`
